export enum FontKeys {
	DMSansBlack = 'DMSansBlack',
	DMSansBlackItalic = 'DMSansBlackItalic',
	DMSansBold = 'DMSansBold',
	DMSansBoldItalic = 'DMSansBoldItalic',
	DMSansExtraBold = 'DMSansExtraBold',
	DMSansExtraBoldItalic = 'DMSansExtraBoldItalic',
	DMSansLight = 'DMSansLight',
	DMSansMedium = 'DMSansMedium',
	DMSansMediumItalic = 'DMSansMediumItalic',
	DMSansRegular = 'DMSansRegular',
	DMSansSemiBold = 'DMSansSemiBold',
	DMSansSemiBoldItalic = 'DMSansSemiBoldItalic',
	DMSansThin = 'DMSansThin',
	DMSansThinItalic = 'DMSansThinItalic',
}
